<?php
/** @var Worldline\Payment\Block\Adminhtml\System\Config\EraseDebugLog $block */
?>
<td class="label">
    <label for="<?= $block->escapeHtml($block->getHtmlId()) ?>"></label>
</td>
<td class="value">
    <button class="scalable"
            type="button"
            id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"
            onclick="window.location.href='<?= $block->escapeUrl($block->getAjaxUrl()) ?>'"
    >
        <span id="<?= $block->getHtmlId() ?>_result"><?= $block->escapeHtml($block->getLabel()) ?></span>
    </button>
</td>
